import { createApp } from 'vue';
import App from './App.vue';
import router from './router/index';
import 'virtual:windi.css';
import 'virtual:svg-icons-register';
import { createPinia } from 'pinia';
const pinia = createPinia();
const app = createApp(App);
app.use(pinia);
app.use(router);
app.mount('#app');
